version: "2"

services:
    mesaic:
        extends:
            file: docker-compose.yml
            service: mesaic
        links:
          - database
        ports:
          - "80:3000"
        environment:
          - NODE_ENV=production

    database:
        extends:
            file: docker-compose.yml
            service: database
        restart: always
        volumes:
        - "data:/var/lib/mysql"

volumes:
    data:
