version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: node:10.14.2-slim
        steps:
            - checkout

            - run:
                name: Install greenkeeper-lockfile
                command: sudo yarn install -g greenkeeper-lockfile@1

            # restore node_modules from cache
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

            - run:
                name: Install Dependencies
                command: yarn install

            - run:
                name: greenkeeper-lockfile update
                command: greenkeeper-lockfile-update

            # save node_modules in cache
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules

            - run:
                name: Run Linter
                command: yarn lint

            - run:
                name: Run unit tests
                command: |
                    yarn test

            - run:
                name: greenkeeper-lockfile upload
                command: greenkeeper-lockfile-upload

            - setup_remote_docker

            - run:
                name: Install docker-compose
                command: |
                  set -x
                  curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                  chmod +x ~/docker-compose
                  sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run:
                name: Run borderbulk tests and push the docker image.
                command: |
                  if [ -z ${CIRCLE_TAG+x} ]; then
                    DOCKER_TAG=${CIRCLE_BRANCH}
                  else
                    DOCKER_TAG=${CIRCLE_TAG}
                  fi
                  set -eu
                  docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
                  docker-compose -f docker-compose.prod.yml run --rm sut
                  if [[ ! ${DOCKER_TAG} =~ ^greenkeeper ]]; then
                    docker tag mesaic bern/mesaic:${DOCKER_TAG}
                    docker push bern/mesaic:${DOCKER_TAG}
                  fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
